<?php

/**
 * @file
 * Integrates the Usersnap Web Feedback Tool into Drupal.
 */

/**
 * Implements hook_menu().
 */
function usersnap_menu() {
  $items = array();
  $items['admin/config/services/usersnap'] = array(
    'title' => 'Usersnap Settings',
    'description' => 'Enter yout Usersnap API Key to use the Web Feedback Service',
    'file' => 'usersnap.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('usersnap_admin'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 0,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function usersnap_permission() {
  return array(
    'usersnap' => array(
      'title' => t('Access Usersnap'), 
      'description' => t('Embeds the Usersnap JS and API Key for the role.'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function usersnap_init() {
  if (user_access('usersnap')) {
    add_usersnap();
  }
}

/**
 * Helper function to add usersnap widget to the current page.
 */
function add_usersnap() {
  $apikey = variable_get('usersnap_apikey', '');
  $position = explode('_', variable_get('usersnap_position', 'bottom_right'));
  $language = variable_get('usersnap_language', 'en');
  $button_text = variable_get('usersnap_button_text', 'Feedback');
  $show_cbox = variable_get('usersnap_show_comment_box', FALSE);
  $cbox_placeholder = variable_get('usersnap_comment_box_placeholder', '');
  $cbox_required = variable_get('usersnap_comment_box_required', FALSE);
  $show_email = variable_get('usersnap_show_email_field', FALSE);
  $email_placeholder = variable_get('usersnap_email_field_placeholder', '');
  $email_required = variable_get('usersnap_email_field_required', FALSE);

  $js = <<<'JS'
var _usersnapconfig = {
		apiKey: Drupal.settings.usersnap.apikey,
		btnText: Drupal.settings.usersnap.button,
		lang: Drupal.settings.usersnap.language,
		valign: Drupal.settings.usersnap.valign,
		halign: Drupal.settings.usersnap.halign,
		emailBox: Drupal.settings.usersnap.email,
		emailBoxPlaceholder: Drupal.settings.usersnap.eplaceholder,
		emailRequired: Drupal.settings.usersnap.erequired,
		commentBox: Drupal.settings.usersnap.cbox,
		commentBoxPlaceholder: Drupal.settings.usersnap.cplaceholder,
		commentRequired: Drupal.settings.usersnap.crequired
	};
	(function() {
	    var s = document.createElement('script');
	    s.type = 'text/javascript';
	    s.async = true;
	    s.src = '//api.usersnap.com/usersnap.js';
	    var x = document.getElementsByTagName('head')[0];
	    x.appendChild(s);
	})();
JS;

  drupal_add_js($js, array(
    'type' => 'inline',
    'scope' => 'footer',
    'weight' => 5,
  ));
  drupal_add_js(array(
    'usersnap' => array(
      'apikey' => $apikey,
      'language' => $language,
      'button' => $button_text,
      'valign' => $position[0],
      'halign' => $position[1],
      'cbox' => $show_cbox,
      'cplaceholder' => $cbox_placeholder,
      'crequired' => $cbox_required,
      'email' => $show_email,
      'eplaceholder' => $email_placeholder,
      'erequired' => $email_required,
    )
  ), 'setting');
}
